name: clinical-survival-ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.24
  - pandas>=2.0
  - scikit-learn>=1.3
  - scikit-survival>=0.21
  - lifelines>=0.27
  - xgboost>=1.7
  - shap>=0.43
  - matplotlib>=3.7
  - seaborn>=0.12
  - pip
  - pydantic>=2.0
  - mlflow>=2.0
  - pip:
      - pyyaml>=6.0
      - jinja2>=3.1
      - pytest>=7.4
      - ruff>=0.5
      - black>=24.4
      - python-json-logger>=2.0
